language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xrchitron/vue-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xrchitron/vue-test npm test

after_success:
  - docker build -t xrchitron/itineraryx-client ./client
  - docker build -t xrchitron/itineraryx-nginx ./nginx
  - docker build -t xrchitron/itineraryx-server ./server
  - docker build -t xrchitron/itineraryx-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push xrchitron/itineraryx-client
  - docker push xrchitron/itineraryx-nginx
  - docker push xrchitron/itineraryx-server
  - docker push xrchitron/itineraryx-worker

# deploy:
#   provider: elasticbeanstalk
#   region: 'ap-northeast-1'
#   app: 'itineraryx-docker'
#   env: 'Itineraryx-docker-env'
#   bucket_name: 'elasticbeanstalk-ap-northeast-1-343534424551' #S3 bucket name
#   bucket_path: 'docker-itineraryx' #same as app name
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY